name: Deploy Automático na Locaweb

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Pegando o código mais recente
        uses: actions/checkout@v4

      - name: 2. Preparando o computador da nuvem
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 3. Construindo o Layout novo (Build)
        run: |
          npm install
          npm run build

      - name: 4. Copiando a vitrine pronta para a Locaweb
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          source: "dist/*" 
          target: "/var/www/breww.live/html/"
          strip_components: 1
